[versions]
androidVersion = "9.1.0-alpha04"
androidCacheFixVersion = "3.0.3"
cronetApiVersion = "143.7445.0"
kspVersion = "2.3.3"
moshixVersion = "0.33.0"
dependenciesUpdateVersion = "0.53.0"
dexcountVersion = "4.0.0"
androidRetrofixVersion = "1.0.0"
activityVersion = "1.12.2"
adsAdservicesVersion = "1.1.0-beta12"
annotationExperimentalVersion = "1.6.0-alpha01"
annotationVersion = "1.9.1"
benchmarkVersion = "1.5.0-alpha01"
composeVersion = "1.11.0-alpha02"
collectionVersion = "1.6.0-alpha01"
concurrentFuturesKtxVersion = "1.3.0"
coordinatorlayoutVersion = "1.3.0"
coreKtxVersion = "1.17.0"
customviewVersion = "1.2.0"
desugarLibsVersion = "2.1.5"
espressoCoreVersion = "3.7.0"
exifinterfaceVersion = "1.4.2"
fragmentVersion = "1.8.9"
coroutinesVersion = "1.10.2"
junitVersion = "1.3.0"
kotlinxSerializationVersion = "1.10.0-RC"
lifecycleVersion = "2.10.0"
loaderVersion = "1.1.0"
composeMaterial3Version = "1.5.0-alpha11"
playServicesAdsIdentifierVersion = "18.2.0"
playServicesAppsetVersion = "16.1.0"
playServicesBaseVersion = "18.10.0"
playServicesCronetVersion = "18.1.1"
playServicesLocationVersion = "21.3.0"
playServicesTasksVersion = "18.4.1"
playServicesTimeVersion = "16.0.1"
profileinstallerVersion = "1.4.1"
rulesVersion = "1.7.0"
streamsupportVersion = "1.7.4"
leakcanaryVersion = "2.14"
kotlinVersion = "2.3.0"
splittiesVersion = "3.0.0"
accompanistVersion = "0.37.3"
okioVersion = "3.16.4"
moshiVersion = "1.15.2"
mmkvVersion = "2.3.0"
relinkerVersion = "1.4.5"
proguardVersion = "7.8.2"
hmsVersion = "3.4.83.301"
mcsVersion = "1.0.3.300"
firebaseInstallationVersion = "19.0.1"
#noinspection NewerVersionAvailable
tencentMapSdkVersion = "7.6.1.4"
pointLocationVersion = "5.0.1"
apacheCommonsVersion = "3.20.0"
tracingKtxVersion = "1.3.0"
tracingPerfettoVersion = "1.0.1"
truetimeVersion = "4.0.0.alpha"
byteunitsVersion = "0.9.1"
conscryptVersion = "2.5.3"
junit = "4.13.2"
uiautomatorVersion = "2.4.0-alpha07"
versionedparcelableVersion = "1.2.1"
viewpagerVersion = "1.1.0"
windowVersion = "1.6.0-alpha01"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityVersion" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotationVersion" }
androidx-annotation-experimental = { module = "androidx.annotation:annotation-experimental", version.ref = "annotationExperimentalVersion" }
androidx-benchmark-macro-junit4 = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "benchmarkVersion" }
androidx-compose-animation = { module = "androidx.compose.animation:animation", version.ref = "composeVersion" }
androidx-coordinatorlayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "coordinatorlayoutVersion" }
androidx-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycleVersion" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "rulesVersion" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exifinterfaceVersion" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "composeVersion" }
androidx-compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "composeVersion" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleVersion" }
androidx-loader = { module = "androidx.loader:loader", version.ref = "loaderVersion" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "composeMaterial3Version" }
androidx-compose-material3-window-size = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "composeMaterial3Version" }
androidx-privacysandbox-adservices = { module = "androidx.privacysandbox.ads:ads-adservices", version.ref = "adsAdservicesVersion" }
androidx-collection = { module = "androidx.collection:collection", version.ref = "collectionVersion" }
androidx-concurrent-futures-ktx = { module = "androidx.concurrent:concurrent-futures-ktx", version.ref = "concurrentFuturesKtxVersion" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
androidx-customview = { module = "androidx.customview:customview", version.ref = "customviewVersion" }
androidx-fragment-compose = { module = "androidx.fragment:fragment-compose", version.ref = "fragmentVersion" }
androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "profileinstallerVersion" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "composeVersion" }
androidx-compose-runtime-tracing = { module = "androidx.compose.runtime:runtime-tracing", version.ref = "composeVersion" }
androidx-compose-ui-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "composeVersion" }
androidx-tracing-ktx = { module = "androidx.tracing:tracing-ktx", version.ref = "tracingKtxVersion" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "composeVersion" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "composeVersion" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeVersion" }
androidx-tracing-perfetto = { module = "androidx.tracing:tracing-perfetto", version.ref = "tracingPerfettoVersion" }
androidx-tracing-perfetto-binary = { module = "androidx.tracing:tracing-perfetto-binary", version.ref = "tracingPerfettoVersion" }
androidx-test-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomatorVersion" }
androidx-versionedparcelable = { module = "androidx.versionedparcelable:versionedparcelable", version.ref = "versionedparcelableVersion" }
androidx-viewpager = { module = "androidx.viewpager:viewpager", version.ref = "viewpagerVersion" }
androidx-window = { module = "androidx.window:window", version.ref = "windowVersion" }
cronet-api = { module = "org.chromium.net:cronet-api", version.ref = "cronetApiVersion" }
desugar-libs-nio = { module = "com.android.tools:desugar_jdk_libs_nio", version.ref = "desugarLibsVersion" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutinesVersion" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "coroutinesVersion" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutinesVersion" }
kotlinx-serialization-json-okio = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-okio", version.ref = "kotlinxSerializationVersion" }
play-services-ads-identifier = { module = "com.google.android.gms:play-services-ads-identifier", version.ref = "playServicesAdsIdentifierVersion" }
play-services-appset = { module = "com.google.android.gms:play-services-appset", version.ref = "playServicesAppsetVersion" }
play-services-base = { module = "com.google.android.gms:play-services-base", version.ref = "playServicesBaseVersion" }
play-services-cronet = { module = "com.google.android.gms:play-services-cronet", version.ref = "playServicesCronetVersion" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocationVersion" }
play-services-tasks = { module = "com.google.android.gms:play-services-tasks", version.ref = "playServicesTasksVersion" }
play-services-time = { module = "com.google.android.gms:play-services-time", version.ref = "playServicesTimeVersion" }
streamsupport-android-retrofuture = { module = "net.sourceforge.streamsupport:android-retrofuture", version.ref = "streamsupportVersion" }
streamsupport-android-retrostreams = { module = "net.sourceforge.streamsupport:android-retrostreams", version.ref = "streamsupportVersion" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanaryVersion" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlinVersion" }
splitties-appctx = { module = "com.louiscad.splitties:splitties-appctx", version.ref = "splittiesVersion" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistVersion" }
okio = { module = "com.squareup.okio:okio", version.ref = "okioVersion" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshiVersion" }
mmkv = { module = "com.tencent:mmkv", version.ref = "mmkvVersion" }
relinker = { module = "com.getkeepsafe.relinker:relinker", version.ref = "relinkerVersion" }
proguard-retrace = { module = "com.guardsquare:proguard-retrace", version.ref = "proguardVersion" }
huawei-ads-identifier = { module = "com.huawei.hms:ads-identifier", version.ref = "hmsVersion" }
hihonor-ads-identifier = { module = "com.hihonor.mcs:ads-identifier", version.ref = "mcsVersion" }
firebase-installations = { module = "com.google.firebase:firebase-installations", version.ref = "firebaseInstallationVersion" }
tencentLocationSdk = { module = "com.tencent.map.geolocation:TencentLocationSdk-openplatform", version.ref = "tencentMapSdkVersion" }
pointlocation6709 = { module = "us.fatehi:pointlocation6709", version.ref = "pointLocationVersion" }
apache-commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "apacheCommonsVersion" }
truetime-android = { module = "com.github.instacart:truetime-android", version.ref = "truetimeVersion" }
byteunits = { module = "com.jakewharton.byteunits:byteunits", version.ref = "byteunitsVersion" }
conscrypt-android = { module = "org.conscrypt:conscrypt-android", version.ref = "conscryptVersion" }
junit = { module = "junit:junit", version.ref = "junit" }
ben-manes-versions-fix = { module = "com.github.dc-abuettgenbach.gradle-versions-plugin:com.github.ben-manes.versions.gradle.plugin", version = "fix~concurrent-modification-exception-gradle9-SNAPSHOT" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidVersion" }
android-library = { id = "com.android.library", version.ref = "androidVersion" }
android-test = { id = "com.android.test", version.ref = "androidVersion" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinVersion" }
android-cache-fix = { id = "org.gradle.android.cache-fix", version.ref = "androidCacheFixVersion" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kspVersion" }
androidx-baselineprofile = { id = "androidx.baselineprofile", version.ref = "benchmarkVersion" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinVersion" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinVersion" }
moshix = { id = "dev.zacsweers.moshix", version.ref = "moshixVersion" }
ben-manes-versions = { id = "com.github.ben-manes.versions", version.ref = "dependenciesUpdateVersion" }
dexcount = { id = "com.getkeepsafe.dexcount", version.ref = "dexcountVersion" }
android-retrofix = { id = "com.github.sgtsilvio.gradle.android-retrofix", version.ref = "androidRetrofixVersion" }